[package]
name = "const-config-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
serde = "1.0"
toml = { version = "0.8", optional = true, features = ["parse", "preserve_order"] }
serde_json = { version = "1.0", optional = true }
serde_yml = { version = "0.0.12", optional = true }
ron = { version = "0.10", optional = true }
json5 = { version = "0.4", optional = true }
serde-lexpr = { version = "0.1", optional = true }
deser-hjson = { version = "2.2", optional = true }
csv = { version = "1.3", optional = true }
ciborium = { version = "0.2", optional = true }
rmp-serde = { version = "1.3", optional = true }
serde-pickle = { version = "1.2", optional = true }
bson = { version = "2.14", optional = true }
flexbuffers = { version = "25.2", optional = true }

[features]
default = []
all = [
    "toml",
    "json",
    "yaml",
    "ron",
    "json5",
    "s-expr",
    "hjson",
    "csv",
    "cbor",
    "msgpack",
    "pickle",
    "bson",
    "flexbuffers",
]
toml = ["dep:toml"]
json = ["dep:serde_json"]
yaml = ["dep:serde_yml"]
ron = ["dep:ron"]
json5 = ["dep:json5"]
s-expr = ["dep:serde-lexpr"]
hjson = ["dep:deser-hjson"]
csv = ["dep:csv"]
cbor = ["dep:ciborium"]
msgpack = ["dep:rmp-serde"]
pickle = ["dep:serde-pickle"]
bson = ["dep:bson"]
flexbuffers = ["dep:flexbuffers"]
