[package]
name = "const-config-gen"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0"
serde = "1.0"
toml = { version = "0.8", optional = true, features = ["parse", "preserve_order"] }
serde_json = { version = "1.0", optional = true }
serde_yml = { version = "0.0.12", optional = true }

[features]
default = ["toml", "json", "yaml"]
toml = ["dep:toml"]
json = ["dep:serde_json"]
yaml = ["dep:serde_yml"]
